FROM ubuntu:22.04

# 将环境设置为非交互环境
ENV DEBIAN_FRONTEND=noninteractive

COPY ./src/ /src/

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
    && apt update --no-install-recommends \
    && apt install -y gcc dwarfdump build-essential unzip linux-base kmod

WORKDIR /src

RUN dpkg -i linux-image-unsigned-6.5.0-41-generic-dbgsym_6.5.0-41.41~22.04.2_amd64.ddeb

RUN chmod +x dwarf2json \
    && ./dwarf2json linux --elf /usr/lib/debug/boot/vmlinux-6.5.0-41-generic > Ubuntu_6.5.0-41-generic.json \
    && mv Ubuntu_6.5.0-41-generic.json /tmp